name: Django Student App CI/CD

on:
  push:
    branches: [ main, master ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: django-student-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
    - name: Update Helm Chart
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/k8s-configs
        token: ${{ secrets.GH_PAT }}
        path: k8s-configs
        
    - name: Update image tag in Helm values
      run: |
        cd k8s-configs
        sed -i "s/tag: .*/tag: \"${{ github.sha }}\"/" django-student-app/values.yaml
        
    - name: Commit and push changes
      run: |
        cd k8s-configs
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add django-student-app/values.yaml
        git commit -m "Update image tag to ${{ github.sha }}" || exit 0
        git push
